<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# " lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Using IfcOpenshell and pythonOCC to generate cross sections directly from an IFC file | IfcOpenShell Academy</title>
<link href="../../assets/css/all-nocdn.css" rel="stylesheet" type="text/css">
<link href="../../assets/css/ipython.min.css" rel="stylesheet" type="text/css">
<link href="../../assets/css/nikola_ipython.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
<meta name="theme-color" content="#5670d4">
<meta name="generator" content="Nikola (getnikola.com)">
<link rel="alternate" type="application/rss+xml" title="RSS" hreflang="en" href="../../rss.xml">
<link rel="canonical" href="https://academy.ifcopenshell.org/posts/using-ifcopenshell-and-pythonocc-to-generate-cross-sections-directly-from-an-ifc-file/">
<!--[if lt IE 9]><script src="../../assets/js/html5.js"></script><![endif]--><meta name="author" content="Emiel van Strien">
<link rel="prev" href="../using-the-parsing-functionality-of-ifcopenshell-interactively/" title="Using the parsing functionality of IfcOpenShell interactively" type="text/html">
<link rel="next" href="../creating-a-simple-wall-with-property-set-and-quantity-information/" title="Creating a simple wall with property set and quantity information" type="text/html">
<meta property="og:site_name" content="IfcOpenShell Academy">
<meta property="og:title" content="Using IfcOpenshell and pythonOCC to generate cross sections directly f">
<meta property="og:url" content="https://academy.ifcopenshell.org/posts/using-ifcopenshell-and-pythonocc-to-generate-cross-sections-directly-from-an-ifc-file/">
<meta property="og:description" content="[This article contains several snippets of source code for illustration purposes, the full source code can be downloaded at the bottom]
Section information can be used for multiple purposes. This exam">
<meta property="og:type" content="article">
<meta property="article:published_time" content="2015-03-04T05:39:00+02:00">
<meta property="article:tag" content="IfcOpenShell">
<meta property="article:tag" content="python">
<meta property="article:tag" content="PythonOCC">
</head>
<body>
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>

<!-- Header and menu bar -->
<div class="container">
      <header class="blog-header py-3"><div class="row nbb-header align-items-center">
          <div class="col-md-3 col-xs-2 col-sm-2" style="width: auto;">
            <button class="navbar-toggler navbar-light bg-light nbb-navbar-toggler" type="button" data-toggle="collapse" data-target=".bs-nav-collapsible" aria-controls="bs-navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse bs-nav-collapsible bootblog4-search-form-holder">
                
            </div>
        </div>
          <div class="col-md-6 col-xs-10 col-sm-10 bootblog4-brand" style="width: auto;">
            <a class="navbar-brand blog-header-logo text-dark" href="../../">

            <span id="blog-title">IfcOpenShell Academy</span>
        </a>
          </div>
            <div class="col-md-3 justify-content-end align-items-center bs-nav-collapsible collapse flex-collapse bootblog4-right-nav">
            <nav class="navbar navbar-light bg-white"><ul class="navbar-nav bootblog4-right-nav">
<li class="nav-item">
    <a href="index.md" id="sourcelink" class="nav-link">Source</a>
    </li>


                    
            </ul></nav>
</div>
    </div>
</header><nav class="navbar navbar-expand-md navbar-light bg-white static-top"><div class="collapse navbar-collapse bs-nav-collapsible" id="bs-navbar">
            <ul class="navbar-nav nav-fill d-flex w-100">
<li class="nav-item">
<a href="../../archive.html" class="nav-link">Archive</a>
                </li>
<li class="nav-item">
<a href="../../categories/" class="nav-link">Tags</a>
                </li>
<li class="nav-item">
<a href="../../rss.xml" class="nav-link">RSS feed</a>
                </li>
<li class="nav-item">
<a href="http://ifcopenshell.org" class="nav-link">IfcOpenShell Home тол</a>

                
            </li>
</ul>
</div>
<!-- /.navbar-collapse -->
</nav>
</div>

<div class="container" id="content" role="main">
    <div class="body-content">
        <!--Body content-->
        
        
        
<article class="post-text h-entry hentry postpage" itemscope="itemscope" itemtype="http://schema.org/Article"><header><h1 class="p-name entry-title" itemprop="headline name"><a href="." class="u-url">Using IfcOpenshell and pythonOCC to generate cross sections directly from an IFC file</a></h1>

        <div class="metadata">
            <p class="byline author vcard p-author h-card"><span class="byline-name fn p-name" itemprop="author">
                    <a class="u-url" href="../../authors/emiel-van-strien/">Emiel van Strien</a>
            </span></p>
            <p class="dateline">
            <a href="." rel="bookmark">
            <time class="published dt-published" datetime="2015-03-04T05:39:00+02:00" itemprop="datePublished" title="2015-03-04 05:39">2015-03-04 05:39</time></a>
            </p>
                <p class="commentline">
    
        <a href="#utterances-thread">Comments</a>


            
        </p>
<p class="sourceline"><a href="index.md" class="sourcelink">Source</a></p>

        </div>
        

    </header><div class="e-content entry-content" itemprop="articleBody text">
    <p>[This article contains several snippets of source code for illustration purposes, the full source code can be downloaded at the bottom]</p>
<p>Section information can be used for multiple purposes. This example is the first part of a project in which the aim is to be able to directly send information to a large 3D concrete printer. This printer will be able to print concrete buildings on a 1:1 scale on a building site. The goal is to control the printer directly from an IFC model. Since the printer will print one layer at a time, the first step is to derive section information from an IFC file. This is what this tutorial is about. As an example of the information that can be deduced from a section, the area that needs to be printed is calculated.</p>
<p>This example builds upon some of the concepts in "Using IfcOpenShell and pythonOCC to construct new geometry" and uses the same model of a simple house, called <a href="http://blog.ifcopenshell.org/2012/11/say-hi-to-ifcopenhouse.html">IfcOpenHouse</a>.</p>
<!-- TEASER_END -->

<p><img alt="Building model" src="../../images/Solibri-Building-1024x598.png"></p>
<h3>Opening and viewing an IFC file</h3>
<p>Just like the <a href="http://academy.ifcopenshell.org/using-ifcopenshell-and-pythonocc-to-construct-new-geometry/" title="Using IfcOpenShell and pythonOCC to construct new geometry">other example</a>, the Qt pythonOCC display is shown and an IFC model is read. The elements that have a 3D representation (the instances of IfcProduct subtypes) are extracted and displayed. The IfcOpeningElements, which are a mechanism to extract openings from walls, and the IfcSite are left out. The products along with their shape are added to a list called product_shapes.</p>
<div class="code"><pre class="code literal-block"><span class="c1"># Specify to return pythonOCC shapes from ifcopenshell.geom.create_shape()</span>
<span class="n">settings</span> <span class="o">=</span> <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">settings</span><span class="p">()</span>
<span class="n">settings</span><span class="o">.</span><span class="n">set</span><span class="p">(</span><span class="n">settings</span><span class="o">.</span><span class="n">USE_PYTHON_OPENCASCADE</span><span class="p">,</span> <span class="kc">True</span><span class="p">)</span>

<span class="c1"># Initialize a graphical display window</span>
<span class="n">occ_display</span> <span class="o">=</span> <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">utils</span><span class="o">.</span><span class="n">initialize_display</span><span class="p">()</span>

<span class="c1"># Open the IFC file using IfcOpenShell</span>
<span class="n">ifc_file</span> <span class="o">=</span> <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">open</span><span class="p">(</span><span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">join</span><span class="p">(</span><span class="n">os</span><span class="o">.</span><span class="n">path</span><span class="o">.</span><span class="n">dirname</span><span class="p">(</span><span class="vm">__file__</span><span class="p">),</span> <span class="s2">"IfcOpenHouse.ifc"</span><span class="p">))</span>

<span class="c1"># The geometric elements in an IFC file are the IfcProduct elements. So these are </span>
<span class="c1"># opened and displayed.</span>
<span class="n">products</span> <span class="o">=</span> <span class="n">ifc_file</span><span class="o">.</span><span class="n">by_type</span><span class="p">(</span><span class="s2">"IfcProduct"</span><span class="p">)</span>
<span class="n">product_shapes</span> <span class="o">=</span> <span class="p">[]</span>

<span class="c1"># For every product a shape is created if the shape has a Representation.</span>
<span class="k">for</span> <span class="n">product</span> <span class="ow">in</span> <span class="n">products</span><span class="p">:</span>
    <span class="k">if</span> <span class="n">product</span><span class="o">.</span><span class="n">is_a</span><span class="p">(</span><span class="s2">"IfcOpeningElement"</span><span class="p">)</span> <span class="ow">or</span> <span class="n">product</span><span class="o">.</span><span class="n">is_a</span><span class="p">(</span><span class="s2">"IfcSite"</span><span class="p">):</span> <span class="k">continue</span>
    <span class="k">if</span> <span class="n">product</span><span class="o">.</span><span class="n">Representation</span> <span class="ow">is</span> <span class="ow">not</span> <span class="kc">None</span><span class="p">:</span>
        <span class="n">shape</span> <span class="o">=</span> <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">create_shape</span><span class="p">(</span><span class="n">settings</span><span class="p">,</span> <span class="n">product</span><span class="p">)</span><span class="o">.</span><span class="n">geometry</span>
        <span class="n">product_shapes</span><span class="o">.</span><span class="n">append</span><span class="p">((</span><span class="n">product</span><span class="p">,</span> <span class="n">shape</span><span class="p">))</span>
</pre></div>

<p>In addition, two list are created to calculate the surface area of every cross section and the total area that needs to be printed for the entire building.</p>
<div class="code"><pre class="code literal-block"><span class="c1"># Two list are initialized to calculate the surface area to be printed.</span>
<span class="n">surface_areas_per_section</span> <span class="o">=</span> <span class="p">[]</span>
<span class="n">surface_areas_per_building</span> <span class="o">=</span> <span class="p">[]</span>
</pre></div>

<h3>Creating the horizontal section plane</h3>
<p>In the this part the section information is going to be extracted from the model. The starting_height of the first section can be chosen, along with the maximum_height of the last section and the height_step between the different sections. As long as the current section_height remains under the maximum_height sections are produced. To retrieve a section, a horizontal plane is created with the Z-coordinate set to the current section_height. From this plane a face is created, in this case of 20 x 20 meter (-10, 10, -10, 10). The section_face is displayed along with the model and after that the display is cleared.</p>
<div class="code"><pre class="code literal-block"><span class="c1"># In this part the sections are created. You can enter the starting height, the </span>
<span class="c1"># maximum height and the height difference between each section.</span>
<span class="n">starting_height</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">maximum_height</span> <span class="o">=</span> <span class="mf">1.5</span>
<span class="n">height_step</span> <span class="o">=</span> <span class="mf">0.5</span>

<span class="n">section_height</span> <span class="o">=</span> <span class="n">starting_height</span>
<span class="k">while</span> <span class="n">section_height</span> <span class="o">&lt;=</span> <span class="n">maximum_height</span><span class="p">:</span>
    <span class="nb">print</span> <span class="s2">"Section height          ="</span><span class="p">,</span> <span class="n">section_height</span>

    <span class="c1"># A horizontal plane is created from which a face is constructed to intersect with </span>
    <span class="c1"># the building. The face is transparently displayed along with the building.    </span>
    <span class="n">section_plane</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">gp</span><span class="o">.</span><span class="n">gp_Pln</span><span class="p">(</span>
        <span class="n">OCC</span><span class="o">.</span><span class="n">gp</span><span class="o">.</span><span class="n">gp_Pnt</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">section_height</span><span class="p">),</span>
        <span class="n">OCC</span><span class="o">.</span><span class="n">gp</span><span class="o">.</span><span class="n">gp_Dir</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">)</span>
    <span class="p">)</span>
    <span class="n">section_face</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">BRepBuilderAPI</span><span class="o">.</span><span class="n">BRepBuilderAPI_MakeFace</span><span class="p">(</span><span class="n">section_plane</span><span class="p">,</span> <span class="o">-</span><span class="mi">10</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="o">-</span><span class="mi">10</span><span class="p">,</span> <span class="mi">10</span><span class="p">)</span><span class="o">.</span><span class="n">Face</span><span class="p">()</span>

    <span class="n">section_face_display</span> <span class="o">=</span> <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">utils</span><span class="o">.</span><span class="n">display_shape</span><span class="p">(</span><span class="n">section_face</span><span class="p">)</span>
    <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">utils</span><span class="o">.</span><span class="n">set_shape_transparency</span><span class="p">(</span><span class="n">section_face_display</span><span class="p">,</span> <span class="mf">0.5</span><span class="p">)</span>
    <span class="k">for</span> <span class="n">shape</span> <span class="ow">in</span> <span class="n">product_shapes</span><span class="p">:</span> <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">utils</span><span class="o">.</span><span class="n">display_shape</span><span class="p">(</span><span class="n">shape</span><span class="p">[</span><span class="mi">1</span><span class="p">])</span>
</pre></div>

<p><img alt="The building model with section plane" src="../../images/1-1024x768.png"></p>
<h3>Determining the intersection of the faces</h3>
<p>After creating the shape for the cross section, the intersection with every product of the building is determined. The result of this intersection is a shape that consists multiple loose edges. To be able to retrieve information from the section itтАЩs important to not just have single edges, but connect them into wires and create faces from those wires.</p>
<div class="code"><pre class="code literal-block"><span class="c1"># Each product of the building is intersected with the horizontal face</span>
<span class="k">for</span> <span class="n">product</span><span class="p">,</span> <span class="n">shape</span> <span class="ow">in</span> <span class="n">product_shapes</span><span class="p">:</span>
    <span class="n">section</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">BRepAlgoAPI</span><span class="o">.</span><span class="n">BRepAlgoAPI_Section</span><span class="p">(</span><span class="n">section_face</span><span class="p">,</span> <span class="n">shape</span><span class="p">)</span><span class="o">.</span><span class="n">Shape</span><span class="p">()</span>
</pre></div>

<p><img alt="The generated cross section of the building" src="../../images/2-1024x768.png"></p>
<h3>Creating wires and faces</h3>
<p>For every section between starting_height and maximum_height the elements are intersected with the horizontal face. Since not all elements actually do intersect with the face, for some elements, no edges are reported. For example the windows do not, while they are above the current section plane in their entirety. These elements are filtered out by assuring the length of the list of edges is greater than zero. The unconnected loose edges are joined into wires and then for every wire a face is created and displayed together with the wires. Note that for a single element multiple wires, closed loops of edges, can be reported, which is the case for example for the door, which representation consists of multiple extruded rectangles.</p>
<div class="code"><pre class="code literal-block"><span class="c1"># The edges of the intersection are stored in a list</span>
<span class="n">section_edges</span> <span class="o">=</span> <span class="nb">list</span><span class="p">(</span><span class="n">OCC</span><span class="o">.</span><span class="n">Utils</span><span class="o">.</span><span class="n">Topo</span><span class="p">(</span><span class="n">section</span><span class="p">)</span><span class="o">.</span><span class="n">edges</span><span class="p">())</span>    

<span class="c1"># If the length of the section_edges list is greater than 0 there is an </span>
<span class="c1"># intersection between the plane (at current height) and the product. Only in that </span>
<span class="c1"># case the product needs to be printed. </span>
<span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">section_edges</span><span class="p">)</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">:</span>
    <span class="nb">print</span> <span class="s2">"    </span><span class="si">{:&lt;20}</span><span class="s2">: </span><span class="si">{}</span><span class="s2">"</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">product</span><span class="o">.</span><span class="n">is_a</span><span class="p">(),</span> <span class="n">product</span><span class="o">.</span><span class="n">Name</span><span class="p">)</span>

    <span class="c1"># Open Cascade has a function to turn loose unconnected edges into a list of </span>
    <span class="c1"># connected wires. This function takes handles (pointers) to Open Cascade's native </span>
    <span class="c1"># sequence type. Hence, two sequences and handles, one for the input, one for the </span>
    <span class="c1"># output, are created. </span>
    <span class="n">edges</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">TopTools</span><span class="o">.</span><span class="n">TopTools_HSequenceOfShape</span><span class="p">()</span>
    <span class="n">edges_handle</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">TopTools</span><span class="o">.</span><span class="n">Handle_TopTools_HSequenceOfShape</span><span class="p">(</span><span class="n">edges</span><span class="p">)</span>

    <span class="n">wires</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">TopTools</span><span class="o">.</span><span class="n">TopTools_HSequenceOfShape</span><span class="p">()</span>
    <span class="n">wires_handle</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">TopTools</span><span class="o">.</span><span class="n">Handle_TopTools_HSequenceOfShape</span><span class="p">(</span><span class="n">wires</span><span class="p">)</span>

    <span class="c1"># The edges are copied to the sequence</span>
    <span class="k">for</span> <span class="n">edge</span> <span class="ow">in</span> <span class="n">section_edges</span><span class="p">:</span> <span class="n">edges</span><span class="o">.</span><span class="n">Append</span><span class="p">(</span><span class="n">edge</span><span class="p">)</span>

    <span class="c1"># A wire is formed by connecting the edges</span>
    <span class="n">OCC</span><span class="o">.</span><span class="n">ShapeAnalysis</span><span class="o">.</span><span class="n">ShapeAnalysis_FreeBounds</span><span class="o">.</span><span class="n">ConnectEdgesToWires</span><span class="p">(</span><span class="n">edges_handle</span><span class="p">,</span> <span class="mf">1e-5</span><span class="p">,</span> <span class="kc">True</span><span class="p">,</span> <span class="n">wires_handle</span><span class="p">)</span>
    <span class="n">wires</span> <span class="o">=</span> <span class="n">wires_handle</span><span class="o">.</span><span class="n">GetObject</span><span class="p">()</span>

    <span class="c1"># From each wire a face is created</span>
    <span class="nb">print</span> <span class="s2">"        number of faces = </span><span class="si">%d</span><span class="s2">"</span> <span class="o">%</span> <span class="n">wires</span><span class="o">.</span><span class="n">Length</span><span class="p">()</span>
    <span class="k">for</span> <span class="n">i</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">wires</span><span class="o">.</span><span class="n">Length</span><span class="p">()):</span>
        <span class="n">wire_shape</span> <span class="o">=</span> <span class="n">wires</span><span class="o">.</span><span class="n">Value</span><span class="p">(</span><span class="n">i</span><span class="o">+</span><span class="mi">1</span><span class="p">)</span>
        <span class="n">wire</span> <span class="o">=</span> <span class="n">TopoDS</span><span class="o">.</span><span class="n">wire</span><span class="p">(</span><span class="n">wire_shape</span><span class="p">)</span>
        <span class="n">face</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">BRepBuilderAPI</span><span class="o">.</span><span class="n">BRepBuilderAPI_MakeFace</span><span class="p">(</span><span class="n">wire</span><span class="p">)</span><span class="o">.</span><span class="n">Face</span><span class="p">()</span>

        <span class="c1"># The wires and the faces are displayed</span>
        <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">utils</span><span class="o">.</span><span class="n">display_shape</span><span class="p">(</span><span class="n">wire</span><span class="p">)</span>
        <span class="n">face_display</span> <span class="o">=</span> <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">utils</span><span class="o">.</span><span class="n">display_shape</span><span class="p">(</span><span class="n">face</span><span class="p">)</span>
        <span class="n">ifcopenshell</span><span class="o">.</span><span class="n">geom</span><span class="o">.</span><span class="n">utils</span><span class="o">.</span><span class="n">set_shape_transparency</span><span class="p">(</span><span class="n">face_display</span><span class="p">,</span> <span class="mf">0.5</span><span class="p">)</span>
</pre></div>

<h3>Calculating the area that needs to be printed</h3>
<p>Now the wires and faces for each subtype of IfcProduct are shown. Furthermore, they are available to query for additional information. For example: to calculate the area of each face, the total area for each section and finally the total area that needs to be printed for the whole building. For this purpose, the surface area of each face is added to a list surface_areas_per_section. After completing all products of a section, the sum of this list is calculated which leads to the total section surface area.</p>
<div class="code"><pre class="code literal-block"><span class="c1"># Data about the wire is created to calculate the area</span>
<span class="n">wire_data</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">ShapeExtend</span><span class="o">.</span><span class="n">ShapeExtend_WireData</span><span class="p">(</span><span class="n">wire</span><span class="p">,</span> <span class="kc">True</span><span class="p">,</span> <span class="kc">True</span><span class="p">)</span>
<span class="n">wire_data_handle</span> <span class="o">=</span> <span class="n">OCC</span><span class="o">.</span><span class="n">ShapeExtend</span><span class="o">.</span><span class="n">Handle_ShapeExtend_WireData</span><span class="p">(</span><span class="n">wire_data</span><span class="p">)</span>

<span class="c1"># The surface area of the face is calculated and appended to the list</span>
<span class="n">surface_area</span> <span class="o">=</span> <span class="nb">abs</span><span class="p">(</span><span class="n">OCC</span><span class="o">.</span><span class="n">ShapeAnalysis</span><span class="o">.</span><span class="n">ShapeAnalysis_TotCross2D</span><span class="p">(</span><span class="n">wire_data_handle</span><span class="p">,</span> <span class="n">face</span><span class="p">))</span>
<span class="nb">print</span> <span class="s2">"        surface area    ="</span><span class="p">,</span> <span class="n">surface_area</span>
<span class="n">surface_areas_per_section</span><span class="o">.</span><span class="n">append</span><span class="p">(</span><span class="n">surface_area</span><span class="p">)</span>
</pre></div>

<p>The script will continue as long as there are sections to process and will eventually print the total surface area for all sections. Partial output of the script is provided below.</p>
<div class="code"><pre class="code literal-block"><span class="n">Section</span> <span class="n">height</span>          <span class="o">=</span> <span class="mf">1.0</span>

    <span class="n">IfcWallStandardCase</span> <span class="p">:</span> <span class="n">South</span> <span class="n">wall</span>
        <span class="n">number</span> <span class="n">of</span> <span class="n">faces</span> <span class="o">=</span> <span class="mi">2</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">0.3852</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">0.5652</span>
    <span class="n">IfcWallStandardCase</span> <span class="p">:</span> <span class="n">North</span> <span class="n">wall</span>
        <span class="n">number</span> <span class="n">of</span> <span class="n">faces</span> <span class="o">=</span> <span class="mi">1</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">3.6</span>
    <span class="n">IfcWallStandardCase</span> <span class="p">:</span> <span class="n">East</span> <span class="n">wall</span>
        <span class="n">number</span> <span class="n">of</span> <span class="n">faces</span> <span class="o">=</span> <span class="mi">2</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">1.044</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">0.396</span>
    <span class="n">IfcWallStandardCase</span> <span class="p">:</span> <span class="n">West</span> <span class="n">wall</span>
        <span class="n">number</span> <span class="n">of</span> <span class="n">faces</span> <span class="o">=</span> <span class="mi">1</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">1.1466</span>
    <span class="n">IfcDoor</span>             <span class="p">:</span> <span class="kc">None</span>
        <span class="n">number</span> <span class="n">of</span> <span class="n">faces</span> <span class="o">=</span> <span class="mi">3</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">0.0064</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">0.0064</span>
        <span class="n">surface</span> <span class="n">area</span>    <span class="o">=</span> <span class="mf">0.0258</span>
</pre></div>

<h3>Download source code</h3>
<p>This is a tutorial for an old version of PythonOCC. Download the full source code of this recipe <a href="../../scripts/generate_sections.py">here</a></p>
    </div>
    <aside class="postpromonav"><nav><ul itemprop="keywords" class="tags">
<li><a class="tag p-category" href="../../categories/ifcopenshell/" rel="tag">IfcOpenShell</a></li>
            <li><a class="tag p-category" href="../../categories/python/" rel="tag">python</a></li>
            <li><a class="tag p-category" href="../../categories/pythonocc/" rel="tag">PythonOCC</a></li>
        </ul>
<ul class="pager hidden-print">
<li class="previous">
                <a href="../using-the-parsing-functionality-of-ifcopenshell-interactively/" rel="prev" title="Using the parsing functionality of IfcOpenShell interactively">Previous post</a>
            </li>
            <li class="next">
                <a href="../creating-a-simple-wall-with-property-set-and-quantity-information/" rel="next" title="Creating a simple wall with property set and quantity information">Next post</a>
            </li>
        </ul></nav></aside><section class="comments hidden-print"><h2>Comments</h2>
        
    
        <div data-title="Using IfcOpenshell and pythonOCC to generate cross sections directly from an IFC file" id="utterances-thread"></div>
        <script src="https://utteranc.es/client.js" repo="IfcOpenShell/academy" issue-term="title" label="Comments" theme="github-light" crossorigin="anonymous"></script></section></article><!--End of body content--><footer id="footer">
            Contents ┬й 2024         <a href="mailto:thomas@aecgeeks.com">Thomas Krijnen</a> - Powered by         <a href="https://getnikola.com" rel="nofollow">Nikola</a>         
            
            
        </footer>
</div>
</div>


        <script src="../../assets/js/all-nocdn.js"></script><script>
    baguetteBox.run('div#content', {
        ignoreClass: 'islink',
        captions: function(element){var i=element.getElementsByTagName('img')[0];return i===undefined?'':i.alt;}});
    </script>
</body>
</html>
